### PR TITLE
Cleanup and update the Swift Package Manager branch

### PR DESCRIPTION
**Pull request by pd95**
I wanted to build a Swift Package for "SwiftHoeDown" when I suddenly saw that there is an `spm` branch already containing a rudimentary (=old) Swift Package definition.

I've updated it with Xcode 12 beta 6 everything to swift-tools-version 5.3, hoedown 3.0.7 and run the basic test.
I tagged this version with 0.1.5.

### CODE REVIEW

**Comment by fappelman** [comment]
I have accepted your changes but made some changes after that. With your changes the import became

```swift
import Hoedown
```

instead of 

```swift
import SwiftHoedown
```

I made changes that now make that the import stays `SwiftHoedown`. 

On top of that, unrelated I also removed the demo apps and add an example as command line app.

I have updated the version to `0.2`

**Comment by pd95** [comment]
Thanks, @fappelman! I've updated my branch with your changes too.

But you are that you did your changes on the `master` branch and not on the `spm` branch?

**Comment by fappelman** [comment]
Yes I merged them back in the master branch. Why would that be a bad thing? 

In the past (my pull request is from 2016) I tried to get my changes back to the original author but he is not taking so I now consider this the "master". 

Let me know if there is a flaw in my reasoning.

**Comment by pd95** [comment]
No problem with that reasoning! I just thought you have explicitly separated the swift package manager stuff to not conflict with the existing Carthage version. I.e. support with Carthage and SPM.

I've not used Carthage, therefore it's not a problem to not support it anymore. But as your repository existed already "a bit longer" (2016), it is possible that somebody relies on your work using Carthage.

**Comment by fappelman** [comment]
Understood. If I did still support Carthage it was accidental. The future is SPM and not Carthage.
Thanks for your support.

**Pull request closed without merging**
